<?php

/**
 * @file
 * Contains editablefields.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function editablefields_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the editablefields module.
    case 'help.page.editablefields':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

